### ISSUE TITLE
problem to update Remote plugins

### ISSUE THREAD

**Issue by adrien-barret** [gptlang/CopilotChat.nvim#11]
Hello, 

I installed the dependencies as mentionned and when I try the updateRemotePlugins I have this error:

```
Encountered ModuleNotFoundError loading plugin at /home/hk/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/copilot.py: No module named 'utilities'
Traceback (most recent call last):
  File "/home/hk/.local/lib/python3.11/site-packages/pynvim/plugin/host.py", line 165, in _load
    module = imp.load_module(name, file, pathname, descr)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imp.py", line 235, in load_module
    return load_source(name, filename, file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imp.py", line 172, in load_source
    module = _load(spec)
             ^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
ModuleNotFoundError: No module named 'utilities'
Encountered ModuleNotFoundError loading plugin at /home/hk/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/plugin.py: No module named 'copilot'
Traceback (most recent call last):
  File "/home/hk/.local/lib/python3.11/site-packages/pynvim/plugin/host.py", line 165, in _load
    module = imp.load_module(name, file, pathname, descr)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imp.py", line 235, in load_module
    return load_source(name, filename, file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imp.py", line 172, in load_source
    module = _load(spec)
             ^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
ModuleNotFoundError: No module named 'copilot'
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /home/hk/.local/share/nvim/rplugin.vim
```

Copilot is working as usual for itself

**Comment by gptlang** [comment]
This looks like an issue with pynvim.

Try `pip install pynvim==0.5.0`

**Comment by badrbouslikhin** [comment]
I had the same issue. 

> This looks like an issue with pynvim.
> 
> Try `pip install pynvim==0.5.0`

I had the same issue, this fixed it. Thanks!
