### ISSUE TITLE
Cannot install due to python issues

### ISSUE THREAD

**Issue by ecosse3** [gptlang/CopilotChat.nvim#16]
Hi, thank you for your work. Since I have access to GitHub Copilot I would like to try chat in neovim, but I cannot run this plugin correctly due to error from `:UpdateRemovePlugins` command.

I am using `lazy.nvim` plugin manager and install it like this:

```lua
  {
    "gptlang/CopilotChat.nvim",
    cmd = "CopilotChat",
  },
```

I installed dependencies with `pip`.

I've run `checkhealth` to check if python path is configured correctly:

```markdown
- OK python: `Python 3.11.7`
- OK python3_host_prog: `Python 3.11.7`
- OK RubyGem: `3.3.7`
- OK npm: `10.1.0`
- OK java: `openjdk version "11.0.11" 2021-04-20`
- OK pip: `pip 23.3.2 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)`
- OK python3_host_prog pip: `pip 23.3.2 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)`
- OK python venv: `Ok`

Python 3 provider (optional) ~
- pyenv: Path: /opt/homebrew/Cellar/pyenv/2.3.35/libexec/pyenv
- pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
- WARNING pyenv: Root does not exist: /Users/lukasz.kurpiewski/.pyenv. Ignoring pyenv for all following checks.
- Using: g:python3_host_prog = "/opt/homebrew/bin/python3"
- Executable: /opt/homebrew/bin/python3
- Python version: 3.11.7
- pynvim version: 0.4.3
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV
```

When I run `:UpdateRemotePlugins` after nvim restart I get error:
```markdown
Encountered ModuleNotFoundError loading plugin at /Users/myuser/.config/nvim/rplugin/python3/copilot.py: No module named 'utilities'
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/pynvim/plugin/host.py", line 165, in _load
    module = imp.load_module(name, file, pathname, descr)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/imp.py", line 235, in load_module
    return load_source(name, filename, file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/imp.py", line 172, in load_source
    module = _load(spec)
             ^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
ModuleNotFoundError: No module named 'utilities'

Encountered ModuleNotFoundError loading plugin at /Users/myuser/.config/nvim/rplugin/python3/plugin.py: No module named 'prompts'
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/pynvim/plugin/host.py", line 165, in _load
    module = imp.load_module(name, file, pathname, descr)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/imp.py", line 235, in load_module
    return load_source(name, filename, file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/imp.py", line 172, in load_source
    module = _load(spec)
             ^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
ModuleNotFoundError: No module named 'prompts'

remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /Users/myuser/.local/share/nvim/rplugin.vim

```

What can be the problem?

When I try to use command I get error `Command 'CopilotChat' not found after loading 'CopilotChat.nvim'` of course.

nvim version:
```
NVIM v0.10.0-dev-1988+g1ef60ea65
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377
```

**Comment by gptlang** [comment]
Duplicate:
- #11

**Comment by gptlang** [comment]
I'll update the readme instructions
