### ISSUE TITLE
undefiend variable g:copilot_chat_view_option

### ISSUE THREAD

**Issue by Dante983** [gptlang/CopilotChat.nvim#17]
Hey guys, i'm getting this error for some reason, not sure what the problem is.
It was working initially, but since yesterday, i've been getting this error..

Thanks.
![clipboard_image_22f53bd785e](https://github.com/gptlang/CopilotChat.nvim/assets/51093125/a3aba4db-106e-4a7e-9612-de5e9cf9fe46)

**Comment by jellydn** [comment]
Hi @Dante983 Are you using my fork? if so, please switch to `canary` branch.

```lua
{
    "jellydn/CopilotChat.nvim",
    branch = "canary",
    opts = {},
    build = function()
      vim.defer_fn(function()
        vim.cmd("UpdateRemotePlugins")
        vim.notify("CopilotChat - Updated remote plugins. Please restart Neovim.")
      end, 3000)
    end,
    event = "VeryLazy",
    keys = {
      { "<leader>cce", "<cmd>CopilotChatExplain<cr>", desc = "CopilotChat - Explain code" },
      { "<leader>cct", "<cmd>CopilotChatTests<cr>", desc = "CopilotChat - Generate tests" },
    },
  }
```

**Comment by Dante983** [comment]
Hello @jellydn, I've copied the config you provided and only difference i had had is that i used config = function() and you used build = function().

but everything is working fine now as i can see, so that should be it, not sure what the issue was besides that, but i'm happy :D 

thanks!

**Comment by jellydn** [comment]
Hi @Dante983 based on the https://github.com/folke/lazy.nvim documentation:
 - config: config is executed when the plugin loads
 - build: build is executed when a plugin is installed or updated

So my intention those lines when the plugin installed or updated.

```lua
vim.defer_fn(function()
    vim.cmd("UpdateRemotePlugins")
    vim.notify("CopilotChat - Updated remote plugins. Please restart Neovim.")
end, 3000)
```

**Comment by ecosse3** [comment]
I got this error as well since yesterday. Any solutions?

```vim
error caught in async handler '/Users/me/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/copilot-plugin.py:command:CopilotChat [['r
efactor']]'
Traceback (most recent call last):
  File "/Users/me/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/copilot-plugin.py", line 55, in copilotChat
    view_option = self.nvim.eval("g:copilot_chat_view_option")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pynvim/api/nvim.py", line 319, in eval
    return self.request('nvim_eval', string, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pynvim/api/nvim.py", line 199, in request
    res = self._session.request(name, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pynvim/msgpack_rpc/session.py", line 139, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim:E121: Undefined variable: g:copilot_chat_view_option```

**Comment by jellydn** [comment]
HI @ecosse3 What is your config? Could you try with below?

```lua
return {
    "jellydn/CopilotChat.nvim",
    opts = {
      mode = "split",
      prompts = {
        Explain = "Explain how it works.",
        Review = "Review the following code and provide concise suggestions.",
        Tests = "Briefly explain how the selected code works, then generate unit tests.",
        Refactor = "Refactor the code to improve clarity and readability.",
      },
    },
    build = function()
      vim.defer_fn(function()
        vim.cmd("UpdateRemotePlugins")
        vim.notify("CopilotChat - Updated remote plugins. Please restart Neovim.")
      end, 3000)
    end,
    event = "VeryLazy",
    keys = {
      { "<leader>cce", "<cmd>CopilotChatExplain<cr>", desc = "CopilotChat - Explain code" },
      { "<leader>cct", "<cmd>CopilotChatTests<cr>", desc = "CopilotChat - Generate tests" },
      { "<leader>ccr", "<cmd>CopilotChatReview<cr>", desc = "CopilotChat - Review code" },
      { "<leader>ccR", "<cmd>CopilotChatRefactor<cr>", desc = "CopilotChat - Refactor code" },
    }
}
```

**Comment by ecosse3** [comment]
@jellydn I have exactly that setup and your fork. Was working great until 2 days ago.

```
NVIM v0.10.0-dev-2191+g4e59422e1
Build type: RelWithDebInfo
LuaJIT 2.1.1706032906
pip 23.3.2 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)
Python 3.11.7
pynvim 0.5.0 found when using :checkhealth
```

I have not idea what could be the problem. Copied `rplugin` dir from plugin to my neovim config directory. Runned `:UpdateRemotePlugins`. Updated neovim version to latest. Doesn't work.

**Comment by jellydn** [comment]
It's working for me except for something I've got `Process exited with error code 134` with `CopilotChat` command. cc @gptlang 

> Copied rplugin dir from plugin to my neovim config directory

By the way, you don't need to copy here if you use `lazy.nvim` as plugin manager.

**Comment by gptlang** [comment]
@jellydn Is this only on your fork? I haven't updated for a while. I can take a look

**Comment by gptlang** [comment]
I'm not having any issue on 6a34829fde1970c0b99a7bdf2dc6b35ad0d4dc91. Works perfectly fine

**Comment by jellydn** [comment]
> @jellydn Is this only on your fork? I haven't updated for a while. I can take a look

Thanks @gptlang Yeah, I got 2-3 times yesterday on my fork. Will try to reproduce if  I find the pattern here.

**Comment by k-martynov** [comment]
I have same issue:
<img width="1271" alt="Screenshot 2024-02-02 at 14 56 29" src="https://github.com/gptlang/CopilotChat.nvim/assets/155782110/c0a2fa00-fa76-4009-976c-47bca77e68a8">

I'm using fork from jellydn, here is my config:
```lua
  {
    "zbirenbaum/copilot.lua",
    cmd = "Copilot",
    event = "InsertEnter",
    config = function()
      require("copilot").setup({
        suggestion = { enabled = false },
        panel = { enabled = false },
      })
    end,
  },
  {
    "jellydn/CopilotChat.nvim",
    dependencies = { "zbirenbaum/copilot.lua" },
    opts = {
      mode = "split",
      debug = false,
      prompts = {
        Explain = "Explain how it works.",
        Review = "Review the following code and provide concise suggestions.",
        Tests = "Briefly explain how the selected code works, then generate unit tests.",
        Refactor = "Refactor the code to improve clarity and readability.",
        Spelling = "Please correct any grammar and spelling errors in the following text.",
        Wording = "Please improve the grammar and wording of the following text.",
      },
    },
    build = function()
      vim.defer_fn(function()
        vim.cmd("UpdateRemotePlugins")
        vim.notify("CopilotChat - Updated remote plugins. Please restart Neovim.")
      end, 3000)
    end,
    event = "VeryLazy",
    keys = {
      { "<leader>cce", "<cmd>CopilotChatExplain<cr>",  desc = "CopilotChat - Explain code" },
      { "<leader>cct", "<cmd>CopilotChatTests<cr>",    desc = "CopilotChat - Generate tests" },
      { "<leader>ccr", "<cmd>CopilotChatReview<cr>",   desc = "CopilotChat - Review code" },
      { "<leader>ccR", "<cmd>CopilotChatRefactor<cr>", desc = "CopilotChat - Refactor code" },
      { "<leader>ccS", "<cmd>CopilotChatSpelling<cr>", desc = "CopilotChat - Correct spelling" },
      { "<leader>ccw", "<cmd>CopilotChatWording<cr>",  desc = "CopilotChat - Improve wording" },
    },
    config = function()
      local wk = require("which-key")

      wk.register({
        ["<leader>cc"] = { name = "CopilotChat" },
        ["<leader>e"] = { "<cmd>CopilotChatExplain<cr>", "CopilotChat - Explain code" },
        ["<leader>t"] = { "<cmd>CopilotChatTests<cr>", "CopilotChat - Generate tests" },
        ["<leader>r"] = { "<cmd>CopilotChatReview<cr>", "CopilotChat - Review code" },
        ["<leader>R"] = { "<cmd>CopilotChatRefactor<cr>", "CopilotChat - Refactor code" },
        ["<leader>S"] = { "<cmd>CopilotChatSpelling<cr>", "CopilotChat - Correct spelling" },
        ["<leader>w"] = { "<cmd>CopilotChatWording<cr>", "CopilotChat - Improve wording" },
      })
    end,
  },
```

**Comment by k-martynov** [comment]
> @k-martynov Please see: [jellydn#30](https://github.com/jellydn/CopilotChat.nvim/issues/30)

Thanks! Now it's working!
