### ISSUE TITLE
TypeError: 'type' object is not subscriptable when loading plugins

### ISSUE THREAD

**Issue by Cassius0924** [gptlang/CopilotChat.nvim#18]
I'm encountering an issue when trying to run `:UpdateRemotePlugins` with LunarVim. Here's the error message I'm getting:

```
Encountered TypeError loading plugin at /root/.local/share/lunarvim/site/pack/lazy/opt/CopilotChat.nvim/rplugin/python3/copilot.py: 'type' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pynvim/plugin/host.py", line 193, in _load
    module = _handle_import(directory, name)
  File "/usr/local/lib/python3.8/dist-packages/pynvim/plugin/host.py", line 40, in _handle_import
    return importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
TypeError: 'type' object is not subscriptable

Encountered TypeError loading plugin at /root/.local/share/lunarvim/site/pack/lazy/opt/CopilotChat.nvim/rplugin/python3/plugin.py: 'type' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pynvim/plugin/host.py", line 193, in _load
    module = _handle_import(directory, name)
  File "/usr/local/lib/python3.8/dist-packages/pynvim/plugin/host.py", line 40, in _handle_import
    return importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
TypeError: 'type' object is not subscriptable

Encountered TypeError loading plugin at /root/.local/share/lunarvim/site/pack/lazy/opt/CopilotChat.nvim/rplugin/python3/utilities.py: 'type' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pynvim/plugin/host.py", line 193, in _load
    module = _handle_import(directory, name)
  File "/usr/local/lib/python3.8/dist-packages/pynvim/plugin/host.py", line 40, in _handle_import
    return importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
TypeError: 'type' object is not subscriptable

remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /root/.local/share/lvim/rplugin.vim
```

It seems like the error is happening when the plugin host tries to import the modules, but I'm not sure why. This error occurs for `copilot.py`, `plugin.py`, and `utilities.py`.

Here are the versions of my dependencies：

```
➜  ~ pip show python-dotenv requests pynvim prompt-toolkit
Name: python-dotenv
Version: 1.0.1
Summary: Read key-value pairs from a .env file and set them as environment variables
Home-page: https://github.com/theskumar/python-dotenv
Author: Saurabh Kumar
Author-email: me+github@saurabh-kumar.com
License: BSD-3-Clause
Location: /usr/local/lib/python3.8/dist-packages
Requires:
Required-by:
---
Name: requests
Version: 2.31.0
Summary: Python HTTP for Humans.
Home-page: https://requests.readthedocs.io
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /usr/local/lib/python3.8/dist-packages
Requires: urllib3, certifi, idna, charset-normalizer
Required-by: undetected-chromedriver, g4f, cloud-init
---
Name: pynvim
Version: 0.5.0
Summary: Python client for Neovim
Home-page: http://github.com/neovim/pynvim
Author: Neovim Authors
Author-email: None
License: Apache
Location: /usr/local/lib/python3.8/dist-packages
Requires: msgpack, greenlet
Required-by:
---
Name: prompt-toolkit
Version: 3.0.43
Summary: Library for building powerful interactive command lines in Python
Home-page: https://github.com/prompt-toolkit/python-prompt-toolkit
Author: Jonathan Slenders
Author-email: None
License: None
Location: /usr/local/lib/python3.8/dist-packages
Requires: wcwidth
Required-by:
```

Any help in resolving this issue would be greatly appreciated. Thank you!

**Comment by gptlang** [comment]
>  The tuple[T] syntax only works in Python 3.9 and up.

**Comment by Cassius0924** [comment]
> > The tuple[T] syntax only works in Python 3.9 and up.
> 
> This is an issue with pynvim.

So is this problem solved and what should I do?

**Comment by gptlang** [comment]
Is it possible to update to Python 3.9?

**Comment by Cassius0924** [comment]
Well, thanks for your reply, but I'm not ready to upgrade to Python3.9 yet

**Comment by gptlang** [comment]
These are the lines where the error is occuring:
https://github.com/neovim/pynvim/blob/5f989dfc47d98bba9f98e5ea17bfbe4c995cb0b0/pynvim/plugin/host.py#L29-L40

It uses `importlib` which is part of the standard library. It should not be erroring. Do you have multiple installations of Python?

**Comment by Cassius0924** [comment]
I only have Python 2.7 and Python 3.8

**Comment by gptlang** [comment]
I've opened up an issue on `pynvim`. I don't Python well enough to resolve this.

**Comment by Cassius0924** [comment]
Thank you very much for taking this issue seriously 🙏
